enum SettingsEnum {
  App_Exclusive_Discounts,
  // App_Exclusive_Product_And_Collection,
  Localization,
  Product_Recommendations,
  // White_Label_App,
  Recently_Viewed_List,
  Customizable_Font,
  Product_Search_And_Sort,
  // Mobile_App_Promotion_Banner,
  // App_User_Discounts,
  // Social_Login,
  Smart_Search_Suggestions,
  Maintenance_Mode,
  Currency_Format,
  Guest_Checkout,
  Change_Default_Language,
  Auto_Navigate_To_Cart_Page,
  // Auto_Select_Variants,
  Variant_Specific_Images,
  Display_Vendor_Or_Brand,
  Display_SKU,
  Hide_Out_Of_Stock_Products,
  Display_Price_One_Below_The_Other,
  // Show_Vendor_Name,
  Show_Discount_Percentage,
  // Skip_Login_and_Address,
  // Order_Note,
  Minimum_Cart_Value,
  Disable_Checkout,
  Show_Filter_On_Product_List_Page,
  // Show_Stickers_On_Product_Cell
  Show_Intro_Screen_At_App_Start,
  Enable_Deeplink,
  App_Image_Fit_Type,
  Signup_Phone_Required,
  Show_MetaField_On_Product_Details,
  Show_Max_Price_On_Product_Grid,
  Multi_Store_Option,
  Multi_Currency,
  Enable_Show_Currency_After_Login,
  Enable_Image_Placeholder,
  Enable_draft_order,
  Hide_price_lebel_in_grid,
  Hide_out_Of_stock_product,
  Enable_product_tag_Label,
  Enable_product_lock_feature,
  Enable_product_list_add_button
}
